version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boutique_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nestjs_api
    restart: always
    depends_on:
      - database
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_NAME: boutique_db
      JWT_SECRET: secretKey
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: angular_app
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf



volumes:
  pgdata:
